sonar.projectKey=astradualsystem_sia-frontend_c63c88fa-4f06-4cf2-bfbe-a500aa995f77
sonar.qualitygate.wait=true

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=SIA FE ADS
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.
sonar.exclusions=.gitlab-ci.yml,.gitlab-ci/**/*,*.gitlab-ci.yml,Dockerfile*,*.dockerfile,.dockerignore,docker-compose*.yml
# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8